name: Create and Update Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v2

      # Шаг 2: Создание ZIP-архива сборки
      - name: Create ZIP Archive
        run: |
          zip -r cofemine-sborka.zip ./*

      # Шаг 3: Создание релиза с уникальным тегом
      - name: Create Unique Release
        uses: actions/create-release@v1
        with:
          tag_name: "release-$(date +'%Y%m%d%H%M%S')"
          release_name: "Release $(date +'%Y-%m-%d %H:%M:%S')"
          body: "Этот релиз был автоматически создан."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      # Шаг 4: Обновление тега "latest"
      - name: Update 'latest' Tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag -f latest
          git push origin latest --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Шаг 5: Загрузка ZIP-архива в релиз "latest"
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: cofemine-sborka.zip
          asset_name: cofemine-sborka.zip
          asset_content_type: application/zip
