name: Create Server Release

on:
  push:
    branches:
      - main

jobs:
  create-server-release:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v2

      # Шаг 2: Установка GitHub CLI
      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      # Шаг 3: Генерация уникального тега
      - name: Generate Unique Server Tag
        id: generate_server_tag
        run: |
          BASE_TAG="server-v$(date +'%Y-%m-%d')"
          UNIQUE_SUFFIX=$(date +%s)
          TAG="${BASE_TAG}-${UNIQUE_SUFFIX}"
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "Generated server tag: $TAG"

      # Шаг 4: Создание ZIP-архива серверной сборки
      - name: Create Server ZIP Archive
        run: |
          mkdir -p server-build
          cp -r mods server-build/
          cp forge-installer.jar server-build/
          cp ops.json server-build/
          cd server.properties server-build/
          cd server-build
          zip -r cofemine-server.zip .
          mv cofemine-server.zip ../
          cd ..
          ls -lh cofemine-server.zip

      # Шаг 5: Создание серверного релиза
      - name: Create Server Release
        id: create_server_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.TAG }}
          release_name: "Server Release ${{ env.TAG }}"
          body: "Серверный релиз ${{ env.TAG }}."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      # Шаг 6: Загрузка серверного архива в релиз
      - name: Upload Server Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_server_release.outputs.upload_url }}
          asset_path: cofemine-server.zip
          asset_name: cofemine-server.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      # Шаг 7: Обновление тега 'latest' для серверного релиза
      - name: Update 'latest' Tag for Server
        run: |
          gh release delete latest --yes || true
          gh release create latest \
            cofemine-server.zip \
            --title "Latest Server Release" \
            --notes "This is the latest server release." --latest
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
