name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Generate Unique Tag
        id: generate_tag
        run: |
          BASE_TAG="v$(date +'%Y-%m-%d')"
          TAG=$BASE_TAG
          COUNTER=2

          # Check if the tag already exists
          while gh release view "$TAG" >/dev/null 2>&1; do
            TAG="${BASE_TAG}r${COUNTER}"
            COUNTER=$((COUNTER + 1))
          done

          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "Generated tag: $TAG"

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.TAG }}
          release_name: "Release ${{ env.TAG }}"
          body: "Автоматический релиз ${{ env.TAG }}."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
