name: Test and Merge

on:
  push:
    branches:
      - dev  # Запускать при пуше в ветку dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

        
      - name: Start Forge Test Server
        run: |
          docker run -d --name test-server \
            -v $PWD/mods:/data/mods \
            -e EULA=TRUE \
            -e TYPE=FORGE \
            -e VERSION=1.20.1 \
            -e FORGEVERSION=47.1.0 \
            -p 25566:25565 \
            itzg/minecraft-server:latest
          sleep 360
        
      - name: Check Docker Logs
        run: docker logs test-server
      
      - name: Verify Port Accessibility
        run: nc -zv localhost 25566 || exit 1

      - name: Install mcstatus
        run: |
          pip install mcstatus

      - name: Verify Server is Running
        run: |
          mcstatus localhost:25566 ping || exit 1

  merge:
    needs: test
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Клонируем полный репозиторий, включая все ветки

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Merge dev into main
        run: |
          git checkout main
          git rm --cached forge-installer.jar .github/workflows/test-and-merge.yml || true
          git merge dev --no-ff -X theirs
          git push origin main
