name: Test and Merge

on:
  push:
    branches:
      - dev  # Запускать при пуше в ветку dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

        
      - name: Start Forge Test Server
        run: |
          docker run -d --name test-server \
            -v $PWD/mods:/data/mods \
            -e EULA=TRUE \
            -e TYPE=FORGE \
            -e VERSION=1.20.1 \
            -e FORGEVERSION=47.3.22 \
            -e JVM_OPTS="-Xmx6G -Xms1G" \
            -p 25566:25565 \
            itzg/minecraft-server:latest
          sleep 900
        
      - name: Check Docker Logs
        run: docker logs test-server
      
      - name: Verify Port Accessibility
        run: nc -zv localhost 25566 || exit 1

      - name: Install mcstatus
        run: |
          pip install mcstatus
      - name: Verify Server is Running
        run: |
          mcstatus localhost:25566 ping || exit 1
  merge:
    needs: test
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
  
      - name: Sync mods folder from dev to main
        run: |
          # Переключаемся на ветку main
          git fetch origin main
          git checkout main
  
          # Копируем папку mods из ветки dev
          git checkout dev -- mods
  
          # Добавляем и коммитим изменения
          git add mods
          git commit -m "Sync mods folder from dev to main"
  
          # Пушим изменения в ветку main
          git push origin main

