name: Test and Merge

on:
  push:
    branches:
      - dev  # Запускать при пуше в ветку dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

        
      - name: Start Forge Test Server
        run: |
          docker run -d --name test-server \
            -v $PWD/mods:/data/mods \
            -e EULA=TRUE \
            -e TYPE=FORGE \
            -e VERSION=1.20.1 \
            -e FORGEVERSION=47.3.22 \
            -p 25566:25565 \
            itzg/minecraft-server:latest
          sleep 900
        
      - name: Check Docker Logs
        run: docker logs test-server
      
      - name: Verify Port Accessibility
        run: nc -zv localhost 25566 || exit 1

      - name: Install mcstatus
        run: |
          pip install mcstatus
      - name: Verify Server is Running
        run: |
          mcstatus localhost:25566 ping || exit 1
  merge:
    needs: test
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Push changes from dev to main
        run: |
          git checkout dev
          git checkout -b temp-main
          git rm -r --cached .github/workflows/ # Удалить workflow-файлы из индекса
          git commit -m "Remove workflows before pushing to main" || echo "No changes to commit"
          git push origin temp-main:main --force # Перезаписываем main новой версией
